// <auto-generated />
namespace ThomasHinesGuitar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class d_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d_));
        
        string IMigrationMetadata.Id
        {
            get { return "201802261906252_d_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
